logging:
  level:
    root: info
    com.cw: debug
server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://192.168.31.142:3306/springdata?characterEncoding=gbk&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      # 更新或者创建数据表结构
      ddl-auto: update